

// export const metadata = {
//   title: "About",
//   description: "Generated by create next app",

import Typography from "@/components/ui/Typography";

// }
export default function AboutPage() {
 
  return (
    <div>
      <h1>About Page</h1>
      <p>This is the About page.</p>
     
     <Typography variant="h1"> xvxcvx</Typography>
      

    </div>
  );
}